### PR TITLE
Fix 3_MCS error - shunt_var

### PR DESCRIPTION
**Pull request by marjanbozorg**
**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

### CODE REVIEW

**Review by klorel — COMMENTED** [review]
OK

**Review by klorel — APPROVED** [review]
Still OK

**Comment by annetill** [comment]
As I said, the unit tests must be updated. @nicolas-pierr can explain or maybe make it.

**Comment by nicolas-pierr** [comment]
For bugs that are inside the model (other than model ouputs), we can't add unit tests. However if you have a simple case that expose the bug. It could be good to link it here. 
Other than that it is ok for me.

**Pull request merged**
