### PR TITLE
Fix NaN in voltage limits override

### PR DESCRIPTION
**Pull request by geofjamg**
**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

### CODE REVIEW

**Comment by geofjamg** [comment]
@annetill it seems that the AMPL model should also be adapted:
```
check[1,672] at line 75 of reactiveopf.mod fails:
  check{(t,s) in SUBSTATIONS: s in BOUND_OVERRIDES} : substation_new_Vmin[s] > 0;
```

**Comment by geofjamg** [comment]
Still remains an error on AMPL side
```
check[1,672] at line 75 of reactiveopf.mod fails:
  check{(t,s) in SUBSTATIONS: s in BOUND_OVERRIDES} : substation_new_Vmin[s] > 0;
```

**Comment by nicolas-pierr** [comment]
Run OpenReac with this network :
```
Network network = IeeeCdfNetworkFactory.create118();
network.getVoltageLevels().iterator().next().setHighVoltageLimit(150);
network.getVoltageLevels().iterator().next().setLowVoltageLimit(Double.NaN);
```
and it will throw without any `VoltageOverride`, I think the problem comes from core and its handling of NaN for high voltage limits.

**Comment by geofjamg** [comment]
> Run OpenReac with this network :
> 
> ```
> Network network = IeeeCdfNetworkFactory.create118();
> network.getVoltageLevels().iterator().next().setHighVoltageLimit(150);
> network.getVoltageLevels().iterator().next().setLowVoltageLimit(Double.NaN);
> ```
> 
> and it will crash without any `VoltageOverride`, I think the problem comes from core and its handling of NaN for high voltage limits.

Ok so you mean also in AMPL export of core, NaN converted to -9999 is not handled correctly on AMPL mode side.

**Pull request merged**
